# Basics
title: Agent JS
description: Documentation for Agent JS

# Paths
baseurl: /agent
layouts_dir: docs/_layouts
includes_dir: docs/_includes
collections_dir: docs/_includes

collections:
  models:

# Theme
remote_theme: just-the-docs/just-the-docs

# Features
search_enabled: true
search:
  heading_level: 3

callouts_level: quiet # or loud
callouts:
  important:
    title: Important
    color: blue

aux_links:
  "Contact":
    - "mailto:vimtaai@inf.elte.hu?subject=Agent%20JS"
  "GitHub":
    - "https://github.com/vimtaai/agent"
